### ISSUE TITLE
Mismatch between latest PyPi version and git tagged version 0.1.4

### ISSUE THREAD

**Issue by hopeemac** [tensorflow/ranking#118]
A pip install of tensorflow-rank==0.1.4 seems to install a prior version. "0.1.3dev" is returned as the version when I run `print(tfr.__version__)`. Also the `input_size` is still a required parameter for the `encode_listwise_features` function even though it is marked as deprecated the function on master.

**Comment by ramakumar1729** [comment]
@hopeemac , thanks for pointing this out. The version number was updated to 0.1.4 in a [commit](https://github.com/tensorflow/ranking/commit/d7e28f8fc0c7a3205820224f16eef65439279670) after the package was uploaded to PyPI, this should have been done before. Since we cannot overwrite the package on PyPI without creating a new version, we will take care of this in subsequent releases.

The change deprecating `input_size` was [added](https://github.com/tensorflow/ranking/compare/v0.1.4...master) to master after the release of tfr-0.1.4. To use the master version of the code, please compile the package from source, as outlined in README.

**Comment by karsures** [comment]
@ramakumar1729 The sparse features demo on colab doesn't work after the commit. This is the error I get:

```encode_listwise_features() takes at least 4 arguments (5 given)```

Is there a quick fix rather than building from source? Thank you.

**Comment by ramakumar1729** [comment]
@karsures Thanks for pointing this out. I've just pushed a new release, the colab should work now. 

@hopeemac : The release for TFR 0.1.5 should address the two concerns you pointed out.

**Comment by lorenzospataro** [comment]
@ramakumar1729 I can see the new release on github but not Pypi: https://pypi.org/project/tensorflow-ranking/#history
When I "pip install --upgrade" I don't get the latest version (0.1.5)...
Is there any way to fix this? Thanks

**Comment by ramakumar1729** [comment]
@lorenzospataro : Thanks for pointing this out. This is fixed.

**Comment by lorenzospataro** [comment]
@ramakumar1729 Great, thank you!
