### ISSUE TITLE
Right way to create vocab.txt for custom dataset (tmdb movie database)

### ISSUE THREAD

**Issue by muthuayyanar** [tensorflow/ranking#192]
Hello TFR Team,

We are trying to use the sample code given in TFR Git to re-rank search engine results for movie dataset.

Looking at the example given in the TFR git, we see for Antique dataset, there is a vocab.txt file and we would like to know the role of vocab.txt and are wondering how to generate the same for our dataset.

we have created tfrecord for the movie dataset and we are not sure how to go about creating vocab.txt to use in the TFR code.

We are relatively new to TF/TFR , sincerely apologize if we are asking novice questions and much appreciate any inputs or point us to some document that can help us here ..

Rgds,

Muthu

**Comment by xuanhuiwang** [comment]
Right now, there is no build-in tokenization technique in TFR. You need to tokenize your data and generate the vocab beforehand as a preprocessing step for your data. So instead of have "this is a sentence", you need to have a bytes_list of "this" "is" "a" "sentence" in your input data. Meanwhile, a vocab like

this
is
a 
sentence

should be provided.

**Comment by muthuayyanar** [comment]
Many tks for your reply/clarification,

Rgds,

Muthu
