### ISSUE TITLE
Why update features when evaluate in model.py

### ISSUE THREAD

**Issue by we1559** [tensorflow/ranking#67]
https://github.com/tensorflow/ranking/blob/8536405845e8ca180dae01c4d0e34ecb1be89b65/tensorflow_ranking/python/model.py#L260

when the mode is  tf.estimator.ModeKeys.PREDICT, it only return list_scores here, but when the mode is  tf.estimator.ModeKeys.EVAL, it will act like  tf.estimator.ModeKeys.TRAIN.
Is that for design? I don't understand why we should update features at any time.
Could anyone explain it for me?

**Comment by xuanhuiwang** [comment]
This is a good question. It is there because of the current design, especially for the `weights` used in losses and metrics. In our loss implementation, we pass the feature name, instead of feature column. So we assume all the features are transformed as needed in our loss and metrics.

We have met the following cases during our development.
1. In order to make the input fn to be consistent for TRAIN and PREDICT, the `features` in model_fn are raw features.
2. We do feature transformation in `transform_fn` and split the features into `context_features` and `example_features`. So the transformed `weights` can be either in these two, but not original `features`. This is why we need to update it.

An alternative way is to pass a feature column definition into losses and metrics and do an additional transformation there. We designed in a way that all feature transformation are centralized.

Hope these make sense.

**Comment by we1559** [comment]
Thanks for your replay.
There is one more question. What does context_features mean? some features in query or some features in session?

> This is a good question. It is there because of the current design, especially for the `weights` used in losses and metrics. In our loss implementation, we pass a feature name, instead of a feature column. So we assume all the features are transformed as needed in our loss and metrics.
> 
> We have met the following cases during our development.
> 
> 1. In order to make the input fn to be consistent for TRAIN and PREDICT, the `features` in model_fn are raw features.
> 2. We do feature transformation in `transform_fn` and split the features into `context_features` and `example_features`. So the transformed `weights` can be either in these two, but not the original `features`. This is why we need to update `features` so that weights can be seen in losses and metrics.
> 
> An alternative way is to pass a feature column definition into losses and metrics and do additional transformations there. We designed in a way that all feature transformation are centralized.
> 
> Hope these make sense.

**Comment by baokunguo** [comment]
in paper( TF-Ranking )，context feature is document-independent features

**Comment by we1559** [comment]
Thanks for your explanation. I get it.
